import type { Product, User } from "@/types"

export const products: Product[] = [
  {
    id: "1",
    name: "Premium Almonds",
    slug: "premium-almonds",
    image: "/placeholder.svg?height=300&width=300",
    description: "High-quality California almonds, rich in protein and healthy fats. Perfect for snacking or cooking.",
    category: "nuts",
    sku: "ALM-001",
    stockQuantity: 100,
    brand: "Krishna Naturals",
    tags: "healthy, protein, premium",
    weights: [
      { label: "250g", price: 299 },
      { label: "500g", price: 549 },
      { label: "1kg", price: 999 },
    ],
    reviews: [
      {
        id: "1",
        userId: "1",
        userName: "Priya Sharma",
        rating: 5,
        comment: "Excellent quality almonds! Fresh and crunchy.",
        date: "2024-01-15",
      },
      {
        id: "2",
        userId: "2",
        userName: "Rajesh Kumar",
        rating: 4,
        comment: "Good quality but slightly expensive.",
        date: "2024-01-10",
      },
    ],
    averageRating: 4.5,
  },
  {
    id: "2",
    name: "Organic Dates",
    slug: "organic-dates",
    image: "/placeholder.svg?height=300&width=300",
    description: "Sweet and nutritious organic dates from Rajasthan. Natural energy booster.",
    category: "dryfruits",
    sku: "DAT-001",
    stockQuantity: 15, // Low stock
    brand: "Krishna Naturals",
    tags: "organic, sweet, energy",
    weights: [
      { label: "250g", price: 199 },
      { label: "500g", price: 349 },
      { label: "1kg", price: 649 },
    ],
    reviews: [
      {
        id: "3",
        userId: "1",
        userName: "Priya Sharma",
        rating: 5,
        comment: "Very sweet and fresh dates. Love them!",
        date: "2024-01-12",
      },
    ],
    averageRating: 5.0,
  },
  {
    id: "3",
    name: "Mixed Seeds",
    slug: "mixed-seeds",
    image: "/placeholder.svg?height=300&width=300",
    description: "Healthy mix of pumpkin, sunflower, and chia seeds. Rich in omega-3 and minerals.",
    category: "seeds",
    sku: "SED-001",
    stockQuantity: 50,
    brand: "Krishna Naturals",
    tags: "omega-3, healthy, mix",
    weights: [
      { label: "100g", price: 149 },
      { label: "250g", price: 299 },
      { label: "500g", price: 549 },
    ],
    reviews: [],
    averageRating: 0,
  },
  {
    id: "4",
    name: "Turmeric Powder",
    slug: "turmeric-powder",
    image: "/placeholder.svg?height=300&width=300",
    description:
      "Pure organic turmeric powder with high curcumin content. Anti-inflammatory and antioxidant properties.",
    category: "spices",
    sku: "TUR-001",
    stockQuantity: 200,
    brand: "Krishna Naturals",
    tags: "organic, curcumin, anti-inflammatory",
    weights: [
      { label: "100g", price: 99 },
      { label: "250g", price: 199 },
      { label: "500g", price: 349 },
    ],
    reviews: [
      {
        id: "4",
        userId: "2",
        userName: "Rajesh Kumar",
        rating: 4,
        comment: "Good quality turmeric with strong aroma.",
        date: "2024-01-08",
      },
    ],
    averageRating: 4.0,
  },
  {
    id: "5",
    name: "Cashew Nuts",
    slug: "cashew-nuts",
    image: "/placeholder.svg?height=300&width=300",
    description: "Premium quality cashew nuts from Kerala. Creamy texture and rich taste.",
    category: "nuts",
    sku: "CAS-001",
    stockQuantity: 80,
    brand: "Krishna Naturals",
    tags: "premium, creamy, kerala",
    weights: [
      { label: "250g", price: 399 },
      { label: "500g", price: 749 },
      { label: "1kg", price: 1399 },
    ],
    reviews: [],
    averageRating: 0,
  },
  {
    id: "6",
    name: "Raisins",
    slug: "raisins",
    image: "/placeholder.svg?height=300&width=300",
    description: "Sweet and juicy raisins, naturally dried grapes. Great for snacking and baking.",
    category: "dryfruits",
    sku: "RAI-001",
    stockQuantity: 5, // Low stock
    brand: "Krishna Naturals",
    tags: "sweet, natural, dried",
    weights: [
      { label: "250g", price: 149 },
      { label: "500g", price: 269 },
      { label: "1kg", price: 499 },
    ],
    reviews: [],
    averageRating: 0,
  },
]

export const users: User[] = [
  {
    id: "1",
    name: "Priya Sharma",
    email: "priya@example.com",
    password: "password123",
    role: "user",
    mobile: "+91 9876543210",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "Rajesh Kumar",
    email: "rajesh@example.com",
    password: "password123",
    role: "user",
    mobile: "+91 9876543211",
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "3",
    name: "Anita Patel",
    email: "anita@example.com",
    password: "password123",
    role: "user",
    mobile: "+91 9876543212",
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "4",
    name: "Admin User",
    email: "admin@krishnanaturals.com",
    password: "admin123",
    role: "admin",
    mobile: "+91 9876543213",
    createdAt: new Date("2024-01-01"),
  },
]

export const categories = [
  { id: "nuts", name: "Nuts", icon: "🥜" },
  { id: "dryfruits", name: "Dry Fruits", icon: "🍇" },
  { id: "seeds", name: "Seeds", icon: "🌰" },
  { id: "spices", name: "Spices", icon: "🌶️" },
]

export const orders = [
  {
    id: "ORD-001",
    userId: "1",
    customerName: "Priya Sharma",
    customerEmail: "priya@example.com",
    customerMobile: "+91 9876543210",
    items: [
      { productId: "1", productName: "Premium Almonds", weight: "500g", price: 549, quantity: 1 },
      { productId: "2", productName: "Organic Dates", weight: "250g", price: 199, quantity: 2 },
    ],
    total: 947,
    status: "pending" as const,
    shippingAddress: {
      name: "Priya Sharma",
      email: "priya@example.com",
      mobile: "+91 9876543210",
      address: "123 Main Street, Andheri West",
      city: "Mumbai",
      pincode: "400058",
    },
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "ORD-002",
    userId: "2",
    customerName: "Rajesh Kumar",
    customerEmail: "rajesh@example.com",
    customerMobile: "+91 9876543211",
    items: [
      { productId: "3", productName: "Mixed Seeds", weight: "250g", price: 299, quantity: 1 },
      { productId: "4", productName: "Turmeric Powder", weight: "100g", price: 99, quantity: 1 },
    ],
    total: 398,
    status: "shipped" as const,
    shippingAddress: {
      name: "Rajesh Kumar",
      email: "rajesh@example.com",
      mobile: "+91 9876543211",
      address: "456 Park Road, Bandra East",
      city: "Mumbai",
      pincode: "400051",
    },
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "ORD-003",
    userId: "3",
    customerName: "Anita Patel",
    customerEmail: "anita@example.com",
    customerMobile: "+91 9876543212",
    items: [{ productId: "5", productName: "Cashew Nuts", weight: "500g", price: 749, quantity: 1 }],
    total: 749,
    status: "delivered" as const,
    shippingAddress: {
      name: "Anita Patel",
      email: "anita@example.com",
      mobile: "+91 9876543212",
      address: "789 Hill View, Powai",
      city: "Mumbai",
      pincode: "400076",
    },
    createdAt: new Date("2024-01-05"),
  },
]
